//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDoAn__Demo1_
{
    using System;
    using System.Collections.Generic;
    
    public partial class EcoFriendlyOrderDetail
    {
        public int ID { get; set; }
        public Nullable<int> IDProduct { get; set; }
        public Nullable<int> IDOrder { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> UnitPrice { get; set; }
    
        public virtual EcoFriendlyOrderPro EcoFriendlyOrderPro { get; set; }
        public virtual EcoFriendlyProduct EcoFriendlyProduct { get; set; }
    }
}
