//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDoAn__Demo1_
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEcoFriendlyStoreEntities : DbContext
    {
        public DBEcoFriendlyStoreEntities()
            : base("name=DBEcoFriendlyStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EcoFriendlyAdminUser> EcoFriendlyAdminUsers { get; set; }
        public virtual DbSet<EcoFriendlyCategory> EcoFriendlyCategories { get; set; }
        public virtual DbSet<EcoFriendlyCustomer> EcoFriendlyCustomers { get; set; }
        public virtual DbSet<EcoFriendlyOrderDetail> EcoFriendlyOrderDetails { get; set; }
        public virtual DbSet<EcoFriendlyOrderPro> EcoFriendlyOrderProes { get; set; }
        public virtual DbSet<EcoFriendlyProduct> EcoFriendlyProducts { get; set; }
    }
}
